### PR TITLE
Merge git-annex branches

### PR DESCRIPTION
**Pull request by rciric**

### CODE REVIEW

**Comment by yarikoptic** [comment]
I would recommend to not submit PRs for git-annex branch.  git-annex uses its own "merge" mechanism, based on the date stamps in the records, so a regular "git merge" employed by github could screw things up eventually.
Just submit your regular PRs, then `git fetch origin; git annex merge; git push origin git-annex` (if origin is the remote where you want to share the git-annex branch)

**Comment by yarikoptic** [comment]
#2 was merged, now just either `git push origin git-annex` or do `datalad publish`

**Comment by rciric** [comment]
Thanks -- it's now pushed! I'll keep this in mind for the future as well

**Comment by yarikoptic** [comment]
Great, FWIW -- all clean for me:
```shell
$> datalad install -g https://github.com/templateflow/tpl-NKI
[INFO   ] Cloning https://github.com/templateflow/tpl-NKI [1 other candidates] into '/tmp/tpl-NKI' 
[INFO   ]   Remote origin not usable by git-annex; setting annex-ignore          
install(ok): /tmp/tpl-NKI (dataset)
action summary:                                                                  
  get (ok: 16)                                                                   
  install (ok: 1)   
```

**Comment by oesteban** [comment]
Same here, thank you both!

**Pull request merged**
